### ISSUE TITLE
Inquiry About Open-Sourcing Model Weights

### ISSUE THREAD

**Issue by JUNJIE99** [rxtan2/Koala-video-llm#2]
Hi, thank you for your great work!

Could you please provide any updates on whether there are plans to release the weights? If so, do you have a tentative timeline for when they might be available?

Thanks.

**Comment by shuyansy** [comment]
Yes, I also want to know when the pretrained weights will be released!

**Comment by rxtan2** [comment]
Hi @JUNJIE99 and @shuyansy , thank you very much for your interest in our work. I have updated the README with the link. Please note that I do not provide the LLama-2 weights and that you will have to download it from HuggingFace.
